### ISSUE TITLE
Question 4

### ISSUE THREAD

**Issue by kskilt** [learn-co-students/phrg-badges-and-schedules-pca-000#2]
The final test on the lab is has a lot of notes but not clear. It is also saying that it is expecting to receive with "line.chomp" but I am not sure what would be chomped. Also by saying "It should puts the list of badges and room assignments" instead of "it should puts the list of badges and the list of room assignments," I was stuck thinking it wanted just 1 list combining both badges and room assignments together instead of just putting one list, and then the next.

**Comment by kskilt** [comment]
@garettarrowood

**Comment by garettarrowood** [comment]
Resolved.
